// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muvqrubnrptbpbsxcdtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11dnFydWJucnB0YnBic3hjZHRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyODIzMTQsImV4cCI6MjA2MTg1ODMxNH0._ytiRKOLRjzwNEOzw_WvyiGlnK68D_LSvfGr5qRFKMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);